version: "3"

services:
  proxy:
    restart: always
    image: "receronp/multi-nginx-231020"
    mem_limit: 128m
    depends_on:
      - api
      - client
    ports:
      - "80:80"

  api:
    image: "receronp/multi-server-231020"
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PG_USER
      - PG_HOST=$PG_HOST
      - PG_DATABASE=$PG_DATABASE
      - PG_PASSWORD=$PG_PASSWORD
      - PG_PORT=$PG_PORT

  client:
    image: "receronp/multi-client-231020"
    mem_limit: 128m
    depends_on:
      - api

  worker:
    image: "receronp/multi-worker-231020"
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
