name: Test Frontend
on:
  pull_request:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t receronp/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true receronp/react-test npm test
